name:        guake-cl
version:     v0.3.0
summary:     change guake's colour scheme
description: change guake's colour scheme

apps:
  guake-cl:
    command: bin/guake-cl

parts:
  guake-cl:
    plugin: nodejs
    node-packages:
      - rgrannell1/guake-cl
